version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Grpc.Tools
    versions:
    - 2.35.0
    - 2.36.0
    - 2.36.1
    - 2.36.4
    - 2.37.0
  - dependency-name: Google.Protobuf
    versions:
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
    - 3.15.8
  - dependency-name: Newtonsoft.Json
    versions:
    - 13.0.1
  - dependency-name: Grpc.Net.Client
    versions:
    - 2.34.0
    - 2.35.0
    - 2.36.0
  - dependency-name: Grpc.AspNetCore.Server
    versions:
    - 2.34.0
    - 2.35.0
    - 2.36.0
